### ISSUE TITLE
Improving tests

### ISSUE THREAD

**Issue by ericagol** [ericagol/celerite.jl#13]
- [x] Create tests for Julia version of celerite, following Python examples by @dfm @giordano

**Comment by giordano** [comment]
I'm trying to move tests from `src` to `test` directory in order to test them with the standard Julia's testing framework.  Is `sturms_theorem.jl` supposed to be used only for tests or is it intended to be part of the source of `celerite.jl`?  Apart from files starting with `test_*`, are there other files that aren't part of the base of `celerite.jl` and should be moved to the `test` directory?

**Comment by ericagol** [comment]
I haven't written a test for sturms_theorem.jl, but it would be good to do it.  This checks for a positive definite covariance matrix when some of the a_j and/or b_j coefficients are negative.  It may be good to add this to the source;  what do you think @dfm ?  I think there is test/ directory;  I'll look at this in a bit.

**Comment by giordano** [comment]
Ok ok, so `sturms_theorem.jl` is part of the code.  I was a bit confused because it's only included by `test_cholesky_ldlt.jl but not by `celerite.jl`.  I'll fix this.  Thanks!

**Comment by giordano** [comment]
Can the files `predict.jl`, `predict_full.jl`, `cholesky_dfm.jl`, and `cholesky_ssm_complex.jl` be removed?  They look like duplicates of functions in `gp.jl`.

**Comment by ericagol** [comment]
Yes, I originally wrote those as separate functions, and then added into the gp.jl 'package.'  That can be done with sturms_theorem.jl as well.
