### ISSUE TITLE
Solver doesn't work for J0=0

### ISSUE THREAD

**Issue by ericagol** [ericagol/celerite.jl#9]
If there are no real terms, then J0=0.  Right now this is not working in the current version of the code.

**Comment by giordano** [comment]
Is there an example to look at?

**Comment by ericagol** [comment]
@giordano Yes, try running include("test_cholesky_ldlt.jl") from the cholesky branch.  You'll notice that with J0=0 (set on line 10, which corresponds to J_real = 0) that the log-determinant from compute_ldlt (in gp.jl, which in turn calls cholesky_ldlt for the low-rank cholesky decomposition without square roots, hence LDLT) does not agree with the determinant computed from the full covariance matrix, while setting J0 > 0 does give agreement.  I haven't debugged this yet, but one place to check is in the loops that involve J_real in cholesky_ldlt routine in gp.jl.

**Comment by giordano** [comment]
<s>At line 53 of `test_cholesky_ldlt.jl` there is the loop
```julia
for i in 2:J0
```
but when `J0=0` the range actually is
```julia
julia> 2:0
2:1
```
If you adapted this loop from a Python/C++ this code is doing something different from expected, because Julia has 1-based indexes.  Can this be the culprit?</s>

I stand corrected, I don't believe this is the issue.

**Comment by giordano** [comment]
I believe I found the issue.  The kernel is initialized in `test_cholesky_ldlt.jl` with
```julia
  kernel = RealTerm(log(aj[1]),log(cj[1]))
  for i=2:J0
    kernel = kernel + RealTerm(log(aj[i]),log(cj[i]))
  end
  for i=J0+1:J
    kernel = kernel + ComplexTerm(log(aj[i]),log(bj[i]),log(cj[i]),log(dj[i]))
  end
```
So the kernel has always a real term, even if `J0=0`.  If I replace this with
```julia
  kernel = ComplexTerm(log(aj[J0+1]),log(bj[J0+1]),log(cj[J0+1]),log(dj[J0+1]))
  for i=J0+2:J
    kernel = kernel + ComplexTerm(log(aj[i]),log(bj[i]),log(cj[i]),log(dj[i]))
  end
  for i=1:J0
    kernel = kernel + RealTerm(log(aj[i]),log(cj[i]))
  end
```
there is no real term and I get the (almost) the same value for the two determinants.  However this wouldn't work with 0 complex terms.

In the end, I believe the issue is in the test code, rather than in the solver, and can be fixed by defining an empty kernel, to which add the real and complex terms.

Does it make sense?

**Comment by ericagol** [comment]
@giordano Yes, I think you are right (I suspected that wasn't a good idea when I wrote it).  Thanks!

**Comment by giordano** [comment]
Hackish fix: in `terms.jl`
```julia
immutable EmptyTerm end

function +(t1::EmptyTerm, t2::Term)
    return TermSum(get_terms(t2))
end

function +(t1::Term, t2::EmptyTerm)
    return TermSum(get_terms(t1))
end
```
and initialize `kernel` with
```julia
kernel = EmptyTerm()
```
and then start the loop for real terms from 1.  However, in this way `kernel` is type-unstable (actually it is type-unstable also as it is now), which is usually a bad practice in Julia, in particular [performance-wise](https://docs.julialang.org/en/stable/manual/performance-tips/#write-type-stable-functions), but may not be so serious in this test code.

I think there is the possibility to improve the code in several places (like use of parametric immutable types for Term subtypes to [avoid fields with abstract types](https://docs.julialang.org/en/stable/manual/performance-tips/#avoid-fields-with-abstract-type)), but this can be done after the functionalities of the package have been established.

**Comment by ericagol** [comment]
@dfm Do you like this solution?

**Comment by dfm** [comment]
I don't think you need an "empty" term unless you actually want to be able
to use celerite for simple chi-squared fitting. The error that you're
seeing is just user error ;-). The user is always required to specify the
kernel so they have to know what it is when they write the code. I would
personally fix your test with an if statement to deal with the J0=0 case
instead of making the language specification more complicated.

If you are worried about type stability, you could probably hack something
and require users to use the TermSum type directly instead of adding and
multiplying terms the way that I wrote it. It's up to you whether or not
the more opaque and complicated interface would be worth a minor
performance for tiny datasets.

**Comment by dfm** [comment]
Sorry! I didn't mean that last bit to come across so aggressive. All I
meant to say was that, in my experience, having a simple, easy to use user
interface goes a long way and it seems unlikely to me that this part of the
code is the bottleneck in any real problem.

**Comment by giordano** [comment]
> It's up to you whether or not the more opaque and complicated interface would be worth a minor performance for tiny datasets.

Yes, as I said, I don't expect it to be a too serious issue ;-)  `gp.kernel`, the object on which calculations are actually performed, is stable.

> It's up to you whether or not the more opaque and complicated interface would be worth a minor performance for tiny datasets.

I tend to agree.  This is a problem on user side, so probably there is no actual need to change the code base.

> Sorry! I didn't mean that last bit to come across so aggressive.

Don't worry, got it ;-)

**Comment by ericagol** [comment]
I fixed this with if & while statements.
